# -*- coding: utf-8 -*-
"""Day2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pLO3SxPOmud6aOnZ_J8vxs_eYEw2_fT3
"""

# 1. MULTIPLICATION TABLE  #

print("Multiplication Tables (1–10):")
for i in range(1, 11):
    print(f"\nTable of {i}")
    for j in range(1, 11):
        print(i, "x", j, "=", i*j)

print("\nMultiplication Tables (11–20):")
for i in range(11, 21):
    print(f"\nTable of {i}")
    for j in range(1, 11):
        print(i, "x", j, "=", i*j)


#  2. FIBONACCI SERIES  #

print("\nFibonacci Series:")
n = 10
a, b = 0, 1
for _ in range(n):
    print(a, end=" ")
    a, b = b, a + b
print()


# 3. ARMSTRONG NUMBER #

num = int(input("\nEnter number to check Armstrong: "))
temp = num
sum_val = 0
digits = len(str(num))

while temp > 0:
    digit = temp % 10
    sum_val += digit ** digits
    temp //= 10

if sum_val == num:
    print("Armstrong Number")
else:
    print("Not an Armstrong Number")


# 4. PRIME NUMBER #

num = int(input("\nEnter number to check Prime: "))

if num <= 1:
    print("Not Prime")
else:
    is_prime = True
    for i in range(2, num):
        if num % i == 0:
            is_prime = False
            break

    if is_prime:
        print("Prime Number")
    else:
        print("Not Prime")


#  5. PALINDROME  #

value = input("\nEnter number/string to check Palindrome: ")

if value == value[::-1]:
    print("Palindrome")
else:
    print("Not Palindrome")