# -*- coding: utf-8 -*-
"""Day6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kpAI9a_eyl2Uyj7ZE6W8PeGshG9iO81m
"""

def security_key(number):
    visible = set()
    repeatednumber = 0
    for ch in str(number):
        if ch in visible:
            repeatednumber += 1
        else:
            visible.add(ch)
    return repeatednumber if repeatednumber > 0 else -1

def securitykey(number):
    s = str(number)
    freq = {}
    for ch in s:
        freq[ch] = freq.get(ch, 0) + 1
    repeatednumber = 0
    for count in freq.values():
        if count > 1:
            repeatednumber += 1
    return repeatednumber if repeatednumber > 0 else -1

number = int(input("Enter a number: "))
print("Repeated digits count:", security_key(number))
print("Repeated digits count (method 2):", securitykey(number))

def odd_even_game(player1, player2):
    if (player1 + player2) % 2 == 0:
        return "Player 1 wins!"
    else:
        return "Player 2 wins!"

player1 = int(input("Player 1, enter your number (0 for even, 1 for odd): "))
player2 = int(input("Player 2, enter your number (0 for even, 1 for odd): "))

result = odd_even_game(player1, player2)
print(result)