# -*- coding: utf-8 -*-
"""Day7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cYJScMLKESWxtGDAKa6imPDM4D6LnghP
"""

def linear_search(list,target):
  for i in range(len(list)):
    if list [i]== target:
      return i
  return - 1
list = [10,20,30,40,50]
target = int(input("enter the target:"))
index = linear_search(list,target)
print("Element found at index:", index)

def linear_search(list,target):
  i = 0
  while i<len(list):
    if list[i] == target:
      return i
    i = i+1
  return -1
list = [10,20,30,40,50]
target = int(input("enter the target:"))
index = linear_search(list,target)
print("Element found at index:", index)

list=[10,20,30,40,50]
# if else condition
target=30
if target in list:
    print("found at index:",list.index(target))
else:
    print("not found")

def binary_search(list,target):
  low=0
  high=len(list)-1
  while low<=high:
    mid=(low+high)//2
    if  list[mid]==target:
      return mid
    elif list[mid]<target:
        low=mid+1
    else:
          high=mid-1
          return -1