# -*- coding: utf-8 -*-
"""Linear task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G0XyFlDafKAzLUS3-YjFgt47JWf8VcWT
"""

def nearest_greater(arr, target):
    greater = None
    for x in arr:
        if x == target:
            return x
        if x > target:
            if greater is None or x < greater:
                greater = x
    return greater if greater is not None else -1


def first_last(arr, target):
    first = -1
    last = -1
    for i in range(len(arr)):
        if arr[i] == target:
            if first == -1:
                first = i
            last = i
    return first, last


def count_positions(arr, target):
    count = 0
    pos = []
    for i in range(len(arr)):
        if arr[i] == target:
            count += 1
            pos.append(i)
    return count, pos


def closest_index(arr, target):
    min_diff = float('inf')
    idx = -1
    for i in range(len(arr)):
        diff = abs(arr[i] - target)
        if diff < min_diff:
            min_diff = diff
            idx = i
    return idx


def mixed_search(arr, target):
    res = []
    for i in range(len(arr)):
        if arr[i] == target and type(arr[i]) == type(target):
            res.append(i)
    return res


def search_2d(arr, target):
    for i in range(len(arr)):
        for j in range(len(arr[i])):
            if arr[i][j] == target:
                return (i, j)
    return -1


def search_both(arr, target):
    left = 0
    right = len(arr) - 1
    while left <= right:
        if arr[left] == target:
            return left
        if arr[right] == target:
            return right
        left += 1
        right -= 1
    return -1


def greater_smaller(arr, target):
    greater = None
    smaller = None
    for x in arr:
        if x > target:
            if greater is None or x < greater:
                greater = x
        if x < target:
            if smaller is None or x > smaller:
                smaller = x
    return greater, smaller


def substring_search(arr, sub):
    res = []
    for i in range(len(arr)):
        if sub in arr[i]:
            res.append(i)
    return res


def skip_k(arr, target, k):
    for i in range(len(arr)):
        if (i + 1) % k == 0:
            continue
        if arr[i] == target:
            return i
    return -1


def rotated_search(arr, target):
    for i in range(len(arr)):
        if arr[i] == target:
            return i
    return -1


def comparisons(arr, target):
    count = 0
    for i in range(len(arr)):
        count += 1
        if arr[i] == target:
            return i, count
    return -1, count


def second_occurrence(arr, target):
    count = 0
    for i in range(len(arr)):
        if arr[i] == target:
            count += 1
            if count == 2:
                return i
    return "Not enough occurrences"


def multi_search(arr, targets):
    result = {}
    for t in targets:
        result[t] = []
        for i in range(len(arr)):
            if arr[i] == t:
                result[t].append(i)
    return result


def longest_string(arr):
    longest = arr[0]
    for i in range(1, len(arr)):
        if len(arr[i]) > len(longest):
            longest = arr[i]
    return longest


def reverse_search(arr, target):
    for i in range(len(arr) - 1, -1, -1):
        if arr[i] == target:
            return i
    return -1


def tolerance_search(arr, target):
    for i in range(len(arr)):
        if abs(arr[i] - target) <= 2:
            return i
    return -1


def circular_search(arr, target, start):
    n = len(arr)
    i = start
    while True:
        if arr[i] == target:
            return i
        i = (i + 1) % n
        if i == start:
            break
    return -1


def max_diff(arr, target):
    max_d = -1
    elem = None
    for x in arr:
        d = abs(x - target)
        if d > max_d:
            max_d = d
            elem = x
    return elem


def search_dict(arr, key, target):
    for i in range(len(arr)):
        if key in arr[i] and arr[i][key] == target:
            return i
    return -1


if __name__ == "__main__":

    arr = [10, 20, 30, 40, 20, 50]
    target = 20

    print("1:", nearest_greater(arr, 25))
    print("2:", first_last(arr, target))
    print("3:", count_positions(arr, target))
    print("4:", closest_index(arr, 26))
    print("5:", mixed_search([10, "10", 10.0], 10))
    print("6:", search_2d([[1,2],[3,4]], 3))
    print("7:", search_both(arr, 40))
    print("8:", greater_smaller(arr, 25))
    print("9:", substring_search(["apple","banana","grape"], "ap"))
    print("10:", skip_k(arr, 40, 3))
    print("11:", rotated_search([30,40,50,10,20], 10))
    print("12:", comparisons(arr, 50))
    print("13:", second_occurrence(arr, 20))
    print("14:", multi_search(arr, [20, 50]))
    print("15:", longest_string(["hi","hello","world"]))
    print("16:", reverse_search(arr, 20))
    print("17:", tolerance_search(arr, 21))
    print("18:", circular_search(arr, 50, 3))
    print("19:", max_diff(arr, 20))
    print("20:", search_dict([{"id":101},{"id":102}], "id", 102))